import enumKeyValuesMatch from '../utils/enumKeyValuesMatch'

export enum FunctionalityCodesEnum {
  ADMIN__CREATE = 'ADMIN__CREATE',
  ADMIN__GET = 'ADMIN__GET',
  ADMIN__RESET_PASSWORD = 'ADMIN__RESET_PASSWORD',

  FACULTY__CREATE = 'FACULTY__CREATE',
  FACULTY__GET_BY_FACULTY_ID = 'FACULTY__GET_BY_FACULTY_ID',
  FACULTY__GET_MANY = 'FACULTY__GET_MANY',
  FACULTY__UPDATE = 'FACULTY__UPDATE',
  FACULTY__DELETE = 'FACULTY__DELETE',

  GROUP__CREATE = 'GROUP__CREATE',
  GROUP__GET_BY_GROUP_ID = 'GROUP__GET_BY_GROUP_ID',
  GROUP__GET_BY_USER_ID = 'GROUP__GET_BY_USER_ID',
  GROUP__GET_BY_FACULTY_ID = 'GROUP__GET_BY_FACULTY_ID',
  GROUP__GET_MANY = 'GROUP__GET_MANY',
  GROUP__UPDATE = 'GROUP__UPDATE',
  GROUP__DELETE = 'GROUP__DELETE',

  SCHEDULE__CREATE = 'SCHEDULE__CREATE',
  SCHEDULE__GET_BY_GROUP_ID = 'SCHEDULE__GET_BY_GROUP_ID',

  NOTE__CREATE = 'NOTE__CREATE',
  NOTE__GET_BY_NOTE_ID = 'NOTE__GET_BY_NOTE_ID',
  NOTE__GET_BY_LESSON_ID = 'NOTE__GET_BY_LESSON_ID',
  NOTE__DELETE = 'NOTE__DELETE',
}

enumKeyValuesMatch(FunctionalityCodesEnum)
