export enum ModuleRoutesEnum {
  SCHEDULE_MODULE = '/schedule',
  GROUP_MODULE = '/groups',
  FACULTY_MODULE = '/faculties',
  NOTE_MODULE = '/notes',
  USER_MODULE = '/users',
  ROLE_MODULE = '/roles',
  FUNCTIONALITY_MODULE = '/functionalities',
  INTERFACE_MODULE = '/interfaces',
  VIEW_MODULE = '/views',
  SETTINGS_MODULE = '/settings',
  APP_VERSION_MODULE = '/app-version',
  CALL_SCHEDULE_MODULE = '/call-schedule',
  SECRET_LABEL_MODULE = '/secret-label',
  SEMESTER_RANGE_DATE_MODULE = '/semester-range-date',
}
